## --- Listeners ---
listeners.wss.default = 8084
listeners.wss.default.ssl_options.certfile   = /opt/emqx/certs/emqx.pem
listeners.wss.default.ssl_options.keyfile    = /opt/emqx/certs/emqx.key
listeners.wss.default.ssl_options.cacertfile = /opt/emqx/certs/ca.pem

