version: '3.8'

services:
  voice2claim-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: voice2claim-service
    env_file:
      - .env
    network_mode: "host"

    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M