version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: gateway
    restart: unless-stopped
    ports:
      - "80:80"
      - "8075:443"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./gateway/conf.d:/etc/nginx/conf.d:ro
      - ./gateway/ssl:/etc/nginx/ssl:ro
      - ./gateway/404.html:/etc/nginx/html/404.html:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - bookwormnet

  voice2claim-service:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: voice2claim-service
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "127.0.0.1:8086:8086"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    networks:
      - bookwormnet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - bookwormnet

  redis:
    image: redis/redis-stack:7.2.0-v16
    container_name: redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    env_file:
      - .env
    networks:
      - bookwormnet

  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASS}
      POSTGRES_DB: ${DB_POSTGRES_NAME}
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./postgres/init/init-v2c.sql:/docker-entrypoint-initdb.d/init-v2c.sql:ro
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bookwormnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_POSTGRES_USER} -d ${DB_POSTGRES_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    command: >
      postgres
        -c shared_buffers=256MB
        -c effective_cache_size=512MB
        -c work_mem=16MB
        -c maintenance_work_mem=128MB
        -c max_connections=100
 
 
  messenger:
    image: emqx/emqx:5.8.0
    container_name: messenger
    hostname: messenger
    restart: unless-stopped
    ports:
      - "127.0.0.1:1883:1883"
      - "8883:8883"       # IoT device cần kết nối trực tiếp từ internet
      - "127.0.0.1:18083:18083"
      - "127.0.0.1:8083:8083"
      - "127.0.0.1:8084:8084"
    volumes:
      - ./messenger/data/emqx1:/opt/emqx/data
      - ./messenger/log/emqx1:/opt/emqx/log
      - ./messenger/certs:/opt/emqx/certs
    environment:
      - EMQX_NODE__NAME=emqx1@emqx1
      - EMQX_LISTENERS__SSL__DEFAULT__ENABLED=true
      - EMQX_LISTENERS__SSL__DEFAULT__BIND=0.0.0.0:8883
      - EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__KEYFILE=/opt/emqx/certs/mqtt_private.key
      - EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__CERTFILE=/opt/emqx/certs/mqtt_public.crt
    networks:
      - bookwormnet

  llmprox-service:
    build:
        context: .
        dockerfile: llm-proxy/Dockerfile
    container_name: llmprox-service
    restart: unless-stopped
    ports:
      - "127.0.0.1:8085:8000"
    networks:
      - bookwormnet

  search-vector:
    build:
      context: ./search-vector   
      dockerfile: Dockerfile
    container_name: search-vector
    restart: unless-stopped
    env_file: .env 
    ports:
      - "127.0.0.1:8087:8001"
    environment:
      - DB_POSTGRES_HOST=postgres
      - EMBEDDING_URL=http://e5_embedding:5004/embed
    networks:
      - bookwormnet

  e5_embedding:
    image: ghcr.io/huggingface/text-embeddings-inference:cuda-latest
    container_name: e5_embedding
    command:
      - --model-id
      - /models--intfloat--multilingual-e5-base/snapshots/835193815a3936a24a0ee7dc9e3d48c1fbb19c55
    ports:
      - "127.0.0.1:5004:80"
    restart: unless-stopped
    networks:
      - bookwormnet
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  redis-data:
  postgres-data:

networks:
  bookwormnet:
    external: true
